# Purpose: this makefile forwards any call to 'make' from the project root dir
# to the 'build' subdirectory generated by CMake.

# List of targets defined in this file
TARGETS_SELF := cmake debug depend run

# Targets not defined in this file
TARGETS_OTHER := $(filter-out $(TARGETS_SELF), $(MAKECMDGOALS))

# If no targets are specified, use the `all` target by default
$(or $(lastword $(TARGETS_OTHER)),all):
	$(MAKE) -C build $(TARGETS_OTHER)
.PHONY: $(TARGETS_OTHER) all

# Do nothing for all targets but last. Also quiet the message "Noting to be done on xxx"
$(filter-out $(lastword $(TARGETS_OTHER)), $(TARGETS_OTHER)):
	@cd .

cmake:
	cd build && cmake ..

debug:
	cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..

depend:
	rm -rf build/external && cd build && cmake ..

run:
	make -C build && ./build/solid

.PHONY: cmake debug depend run
